---
- name: setup vagrant directories, generate Vagrantfile, launch source bax to be provisioned (optionally run provision)
  include: launch-vagrant-box.yml

- name: package provisioned box, update Vagrantfile to reference provisioned box name, and copy both to target directory
  include: package-vagrant-box.yml
